name: elfouad_admin
description: "Elfouad_Admin Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  cupertino_icons: 
  google_fonts: 
  salomon_bottom_bar: 
  google_nav_bar: 
  awesome_drawer_bar:   
   

  # State & Routing
  flutter_bloc: 
  go_router: 

  # Firebase
  firebase_core:
  cloud_firestore: 
  shared_preferences: 

  # Charts/Data
  fl_chart: 
  csv: 
  intl: 
  file_saver: 
  path_provider:
  open_filex: 
  clipboard: 
  excel: 
  share_plus:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: 

flutter_launcher_icons:
  android: true
  image_path: assets/icon/app_icon.png             
  adaptive_icon_background: "#FFFFFF"         
  adaptive_icon_foreground: assets/icon/app_icon.png  

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
