name: elfouad_admin
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  salomon_bottom_bar: ^3.3.2
  google_nav_bar: ^5.0.6
  awesome_drawer_bar: ^1.0.0   # أو آخر إصدار متاح
   # اختياري (لو عايز تبدّل الستايل)

  # State & Routing
  flutter_riverpod: ^3.0.0
  go_router: ^16.2.1

  # Firebase
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  shared_preferences: ^2.5.3

  # Charts/Data
  fl_chart: ^1.1.0
  csv: ^6.0.0
  intl: ^0.20.2
  file_saver: ^0.2.8
  path_provider: ^2.1.4
  open_filex: ^4.4.0
  clipboard: ^0.1.3 
  excel: ^2.1.0
  share_plus:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1  # أو آخر إصدار

flutter_launcher_icons:
  android: true
  image_path: assets/icon.png                 # اللوجو الأساسي
  adaptive_icon_background: "#FFFFFF"         # خلفية للأيقونة المتكيّفة (اختياري لكن مُستحسن)
  adaptive_icon_foreground: assets/icon.png   # ممكن نفس الصورة لو مش عامل layers
  # adaptive_icon_monochrome: assets/icon-mono.png   # اختياري لأندرويد 13+

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

